@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Eduardo",
  "email": "eduardo@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "eduardo@gmail.com",
  "password": "123456"
}

###

# @name get_user_profile
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name insert_flow
POST {{baseUrl}}/flow
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "filePath": "data/flow_data_together.json"
}

###

# @name fetch_flow_by_period
GET {{baseUrl}}/flow
Content-Type: application/json
Authorization: Bearer {{authToken}}
